spring.application.name=SpringBootAIAgent

# allow for us to use multiple AI Chat Clients.
spring.ai.chat.client.enabled=false
spring.main.allow-bean-definition-overriding=true

# get Open AI Api Key from environment var.
spring.ai.openai.api-key=${OPEN_AI_API_KEY}

# Get Google GEN AI Api Key from environment var.
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview

